name: Packer Template Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    name: Packer Format and Validate
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Manually install Packer
      - name: Install Packer
        run: |
          sudo apt-get update && sudo apt-get install -y wget unzip
          wget https://releases.hashicorp.com/packer/1.8.4/packer_1.8.4_linux_amd64.zip
          unzip -o packer_1.8.4_linux_amd64.zip -d /usr/local/bin/

      # Step 3: Run packer fmt --check to ensure no formatting issues
      - name: Check Packer formatting
        run: |
          packer fmt -check -diff .
        # If the packer fmt command makes changes, the workflow will fail.

      # Step 4: Run packer validate to validate the template
      - name: Validate Packer template
        run: |
          packer validate ./ubuntu-24.04.pkr.hcl
