name: Terraform Format and Validate

# Trigger the workflow on pull requests to the main branch
on:
  pull_request:
    branches:
      - main

jobs:
  terraform-format-validate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      # Step 3: Cache Terraform Providers
      - name: Cache Terraform Providers
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugins
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terraform-

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Run Terraform Format Check
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # Step 6: Run Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Step 7: Output validation results
      - name: Show Terraform version
        run: terraform version

      # Ensure any failure in formatting or validation stops the workflow
      - name: Fail the workflow on error
        run: exit 1
        if: failure()
